### PR TITLE
Translation and other small changes to the documentation

### PR DESCRIPTION
**Pull request by frankenstein91**
Hello 

I have adopted your changes and made a few more changes. These include the translation into German and the addition of the picture.
Unfortunately, I could not filter the ArchLinux changes(https://github.com/NaitLee/Cat-Printer/pull/5) in this pull request.

### CODE REVIEW

**Comment by NaitLee** [comment]
Hi, I just found this but I pushed new changes just now 😶‍🌫️
Let me try to solve the conflict...

**Comment by NaitLee** [comment]
Hey, I know there should be a poster but an image put into repo is really a disaster here, the connection to github here is not well, and will fail by chance.

Days ago I put this as github "social poster":
[cat-printer-poster](https://repository-images.githubusercontent.com/403563361/ad018f6e-3a6e-4028-84b2-205f7d35c22b)

```markdown
[![cat-printer-poster](https://repository-images.githubusercontent.com/403563361/ad018f6e-3a6e-4028-84b2-205f7d35c22b)](https://repository-images.githubusercontent.com/403563361/ad018f6e-3a6e-4028-84b2-205f7d35c22b)
```

It will show up on somewhere like search engine result of this repo. I think it's sufficient... 😄

Git keeps file (content) history even if deleted. I don't know if there's workaround...

*Just going to sleep. Stayed up late for many days and really tired... Bye...*

**Comment by frankenstein91** [comment]
That's cute

**Comment by NaitLee** [comment]
Hi,
Changes were actually merged, but I've manually modified something.
I see it's very messy. You may try to make a new branch...

As for pkgbuild file, just leave it there... Thank you...

**Comment by frankenstein91** [comment]
@NaitLee do you think 💬 we should close this pull request?

**Pull request closed without merging**
