### PR TITLE
Fix #58 and add some more configuration information regarding IM Security Policy.

### LINKED ISSUE #58: Error "TypeError: expected str, bytes or os.PathLike object, not NoneType" on command line.
Command executed- 

> image

Output- 

> image

I have tried-

- Checking and creating diary.txt (not empty)

- Power printer on and off

Most likely me doing something wrong, so some help would be fantastic.

### PR DESCRIPTION
**Pull request by nodlek-ctrl**
Hi NaitLee,
I sure hope I am doing this all correct. I added a error message for the NoneType error when IM is not installed. I also edited the readme to explain necessary changes to Imagemagick's security policy. I hope that these fixes are acceptable and I apologize for how long it took; I kept getting distracted by my own printer!
Thanks,
Keldon

### CODE REVIEW

**Comment by NaitLee** [comment]
You are awesome 😄 you shall have “my patch (at least) won’t cause any problem” in mind 😄

Some recommendations, anyway:

It may be wise to wrap up technical instructions in a context like README:

```markdown
<details>
<summary>Further steps</summary>
You may want to *do something hacky* …  
`*execute some commands*`
</details>
```

It would be like this:

<details>
<summary>Further steps</summary>

You may want to *do something hacky* …  
`*execute some commands*`

</details>

P.S. I want to change the default behavior to PF2 now — IM is causing many problems, as I see CLI text printing is a “must try” for newbie hackers 😛 it should be as easy as possible.

---

Besides that, I prefer to put strings into translation files (“i18n”) to localize them — try to put that IM hint to `www/lang/*.json`.

We are all from “not knowing if my contribution is okay,” and we are constantly growing up — just enjoy our life and cute printers 😇

**Comment by nodlek-ctrl** [comment]
Hi again,
Thanks for your help. I'm not quite understanding the localization part. When I change the readme, Do i also have to update the the files in `readme.i18n` as well? I guess I can just google translate it.
Thanks

I would be happy to keep fixing the easy problems to at least clear your plate a bit and give you a break!

**Comment by nodlek-ctrl** [comment]
Alright. Done.
I have localized the error message and added the drop down thingo. I take it that now I have to localize the readme as well?
Thanks.

**Comment by NaitLee** [comment]
Pardon me for a last requirement: only notice user about ImageMagick when it’s needed — it’s not so “mandatory”, only few features want it. There are dedicated functions for them near that place.

For that the notice string need to change, too.

You may just add localization of languages that you have experience in, and leave the left to other volunteers.
(I keep Chinese localization by myself, and its variations are automated.)

FEEL FRE MAK LOLCAT MORE FUN :D

Thank you for contributing! 😉

**Comment by nodlek-ctrl** [comment]
Ohhh gotcha. Ill fix that up. I did wonder if I should do that.

Thanks for your patience with me!

**Comment by nodlek-ctrl** [comment]
Ok. I have now made the error only appear when required. I have also updated the string. One minor error is that the printer does not disconnect from the device after the error is called. I cant use printer.unload because printer is defined later on. I can probably reorder the code, but its getting late and I understand our timezone and availability don't exactly match, so I will leave this here for your review.
Thanks again.

**Comment by NaitLee** [comment]
I feel it’s near the best :)

I could merge this after some test and once you feel it ok :)

For some other reason, I’d like to reorder and change some of the (overall) code by myself.

Thank you 🎉

**Comment by nodlek-ctrl** [comment]
Of course! I have no intention of changing the code too drastically! After all, this is your project and you have the rights to make it work how you like!

Super glad I could help!

**Pull request merged**
